### ISSUE TITLE
Docker container - incorrect handling of arguments (With spaces)

### ISSUE THREAD

**Issue by ajohnstone** [prometheus-junkyard/prometheus_cli#8]
```
docker run --rm -ti prom/prometheus-cli -server="http://grafana.XXX.com:9090/" query 'sum(http_request_size_bytes) by (instance,quantile)'

Usage:
    /bin/prometheus_cli [flags] query <expression>
    /bin/prometheus_cli [flags] query_range <expression> <end_timestamp> <range_seconds> [<step_seconds>]
    /bin/prometheus_cli [flags] metrics

Flags:
  -csv=true: Whether to format output as CSV
  -csvDelimiter=";": Single-character delimiter to use in CSV output
  -server="": URL of the Prometheus server to query
  -timeout=1m0s: Timeout to use when querying the Prometheus server
Please supply a query expression

```

Without using docker.

```
./prometheus_cli -server="http://grafana.XXX.com:9090/" query 'sum(http_request_size_bytes) by (instance,quantile)'
"{instance=""haproxyexporter:9101"", quantile=""0.99""}";297;1437998757.405
"{instance=""containerexporter:9104"", quantile=""0.5""}";299;1437998757.405
"{instance=""graphiteexporter:9108"", quantile=""0.99""}";298;1437998757.405
"{instance=""graphiteexporter:9108"", quantile=""0.5""}";298;1437998757.405
"{instance=""haproxyexporter:9101"", quantile=""0.5""}";297;1437998757.405
"{instance=""containerexporter:9104"", quantile=""0.9""}";299;1437998757.405
"{instance=""containerexporter:9104"", quantile=""0.99""}";299;1437998757.405
"{instance=""haproxyexporter:9101"", quantile=""0.9""}";297;1437998757.405
"{instance=""graphiteexporter:9108"", quantile=""0.9""}";298;1437998757.405
```

Docker image

```
REPOSITORY                                          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
prom/prometheus-cli                                 latest              2beed8e1ef8d        13 days ago         20.23 MB

```

**Comment by juliusv** [comment]
@sdurrheimer

**Comment by sdurrheimer** [comment]
Fixed by sdurrheimer/alpine-golang-make-onbuild@5b76dfa

A manual build of the prom/prometheus-cli image on the docker hub and we are good.

**Comment by juliusv** [comment]
@sdurrheimer Great!

@discordianfish Still can't see any button to trigger a new build on the Docker hub. Are the any more access permissions you can give to user "julius"?

**Comment by discordianfish** [comment]
I've triggered a build manually (requires docker staff account, don't think it's possible for regular users).
I've also added a 'repository link' which will rebuild prometheus-cli every time sdurrheimer/alpine-golang-make-onbuild gets built: https://registry.hub.docker.com/u/prom/prometheus-cli/settings/links/

**Comment by juliusv** [comment]
@discordianfish Cool, thanks! We have to do this with all repos based ontop of that Docker image now, right?

**Comment by discordianfish** [comment]
@juliusv Yes, maybe create an issue for that so we don't forget. I have no time atm.

**Comment by juliusv** [comment]
@discordianfish Done: https://github.com/prometheus/prometheus/issues/937

Closing this issue here.
